export const Constant = {
  HEADER_AUTHORIZATION: 'authorization',
  AUTH_BEARER_TOKEN: 'Bearer ',

  // Account
  ACCOUNT_KIND_ADMIN: 1,
  ACCOUNT_KIND_EMPLOYEE: 2,
  ACCOUNT_KIND_USER: 3,

  // Status
  STATUS_PENDING: 0,
  STATUS_ACTIVE: 1,
  STATUS_LOCK: -1,
  STATUS_DELETED: -2,

  // Notification CMD
  CMD_BROADCAST: 'CMD_BROADCAST',
  CMD_NOTIFICATION_NEW_ORDER: 'CMD_NOTIFICATION_NEW_ORDER'
};
